apiVersion: v1
kind: Service
metadata:
  name: flujo-app-sql
  namespace: namespace-workflow-1710202961877
spec:
  type: LoadBalancer
  selector:
    app: flujo-app-sql
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000